---
- name: Create user
  user:
    name: prometheus
    shell: /sbin/nologin

- name: Download Prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: yes

- name: Move binaries
  copy:
    remote_src: yes
    src: /opt/prometheus-2.52.0.linux-amd64/{{ item }}
    dest: /usr/local/bin/{{ item }}
    mode: 0755
  loop:
    - prometheus
    - promtool

- name: Create config dir
  file:
    path: /etc/prometheus
    state: directory

- name: Create data dir
  file:
    path: /var/lib/prometheus
    state: directory

- name: Copy config
  copy:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml

- name: Setup systemd
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: Enable and start Prometheus
  systemd:
    name: prometheus
    enabled: yes
    state: started
    daemon_reload: yes
